# start project
django-admin startproject mysite

# initial migration
python manage.py migrate

# python manage.py runserver # try out fresh app
python manage.py startapp polls

# add models to polls/models.py

# add polls to installed_apps in mysite/settings.py

# make the changes in models into migrations
python manage.py makemigrations polls

# have a look at the sql generated by migration
python manage.py sqlmigrate polls 0001

# migrate the changes
python manage.py migrate

# play with API
# python manage.py shell

# update urls, views, templates
