# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e433661a04c82b9dbe4ad667a6db2ffc68654ef0f99eb9ef13d05046794eb5e0a9b0b2052c766909fe805a875b7f0b215c749db76f5489a8530636245867bb

test:
  secret_key_base: 448bc3fb71c575ce387b5c128497c1ccf2b52d912a68c98ec958606774b9bda5a7b5984f833ccb6d62c18950cf7e2174af48f2f553797a45f2a2fe39953d1b19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
